<?php
return [
    /*
    |--------------------------------------------------------------------------
    | Strings Language Lines
    |--------------------------------------------------------------------------
    |
    | The following language lines are used in strings throughout the system.
    | Regardless where it is placed, a string can be listed here so it is easily
    | found in a intuitive way.
    |
    */
    'site' => [
        'tag_line' => "La façon la plus facile d'envoyer des textos et courriels à vos participants!",
        'about' => 'À propos',
        'about_activity_messenger' => 'À propos d\'Activity Messenger',
        'about_activity_messenger_details' => 'Activity Messenger est conçu à Montréal. Son fondateur <a href="https://www.linkedin.com/in/martin-drapeau/" target="_blank">Martin Drapeau</a> a été CTO chez <a href="https://www.amilia.com/fr" target="_blank">Amilia</a> pendant 6 ans. Martin a contribué à la conception du produit, à établir la technologie ainsi qu\'à faire grandir l\'entreprise de 15 à 110 personnes.',
        'about_activity_messenger_quote1' => 'La communication est la clé pour une bonne relation avec vos clients. J\'ai appris cette leçon en travaillant avec plusieurs d\'entre vous administrateurs d\'organismes en sport et loisir.',
        'about_activity_messenger_quote2' => 'Avec Activity Messenger je m\'engage à vous donner le meilleur outil de messagerie conçu pour vos besoins. Je vise l\'amélioration des communications que vous aurez avec vos clients ainsi que vos relations avec eux.',
        'join_beta' => 'Devenez un utilisateur BETA',
        'message_participants' => 'Communiquer avec vos participants',
        'main_details' => 'Activity Messenger fait une seule chose - l\'envoi de messages à vos participants et joueurs. Notre mission est de vous permettre d\'envoyer le message parfaitement adapté à vos situations particulières: rappel d\'un match, cours annulé ou campagne marketing ciblée.',
        'main_promo' => 'Inscrivez-vous dès maintenant et obtenez 200 SMS ou 20,000 courriels afin d\'essayer Activity Messenger.',
        'register_now' => 'Inscrivez-vous',
        'list_building' => 'Création de listes avec Amilia',
        'list_building_details' => 'Activity Messenger s\'intègre avec <a href="https://www.amilia.com/fr" target="_blank">Amilia</a>. Faites la sélection de vos participants en choisissant programmations, catégories, sous-catégories et activités. Nous gardons à jour la liste de vos participants. Que ce soit une inscription, un désinscription ou une mise à jour des informations personnelles (courriel ou téléphone mobile), votre liste sera toujours à jour.',
        'list_building_details2' => 'Nous savons que vous passez beaucoup de temps dans Excel afin de filtrer et assembler vos listes. Grâce à l\'intégration Amilia, outrepassez ces étapes. On vous permet de filtrer par âge, genre, anniversaire et même choisir entre parent ou enfant.',
        'import_csv' => 'L\'import CSV simplifié',
        'import_csv_details' => 'Vous n\'avez pas Amilia? Pas de souci, vous pouvez importer une liste en format CSV. Activity Messenger détecte les numéros manquants ou invalides, et vous permet de les réparer sur place ou plus tard.',
        'send_sms' => 'Envoyer des SMS/courriels à vos participants',
        'send_sms_details' => 'Une classe annulée? Un rappel pour un événement spécial? Un changement d\'horaire? Activity Messenger vous permet de leur envoyer un texto et/ou un courriel simplement et rapidement. Si votre message est trop long, ou doit contenir d\'avantage d\'informations, vous pouvez y attacher une page Web en format HTML.',
        'attachments' => 'Attacher des informations et documents',
        'attachments_details' => 'Un texto ou courriel ne peut tout contenir. Activity Messenger vous permet d\'attacher à vos messages un calendrier, une liste, et même un document. Dans ce cas, votre message aura un court hyperlien <code>am.lol</code> redirigeant le participant à une page Web conçu par vous.',
        'track_messages' => 'Suivre la livraison de vos messages',
        'track_messages_details' => 'Acitivity Messenger s\'assure que vos textos/courriels soient reçus. Faites le suivi de l\'état de chacun de vos messages.',
        'pay_as_you_go' => 'Pay As You Go',
        'pay_as_you_go_details' => 'Activity Messenger vous charge 2.5 cents le SMS et 2.5 cents pour 100 courriels. Augmenter votre solde quand vous en avez besoin. Aucune mensualité. Consommez à votre rhythme.',
        'roadmap' => 'Feuille de route',
        'roadmap_details' => 'Nous plannifions l\'ajout de plusieurs fonctionnalités afin de vous simplifier la vie. Par exemple l\'envoi de courriels et l\'intégration à d\'autres plateformes d\'inscription. Consultez la feuille de route et aidez-nous à bâtir le produit de messagerie parfait pour vous.',
        'tell_us' => 'Dites nous quelle est votre platforme actuelle et quels sont vos soucis.',
        'help' => 'Aide',
        'terms_and_conditions' => 'Conditions d\'utilisation',
        'privacy_policy' => 'Politique de confidentialité',
        'register_accept_terms' => 'Vous acceptez les <a href="/terms" target="_blank">Conditions d\'utilisation</a> ainsi que la <a href="/privacy" target="_blank">Politique de confidentialité</a>.',
        'pricing' => 'Tarifs',
        'help' => 'Aide',
    ],
    'roadmap' => [
        'roadmap' => 'Feuille de route',
        'roadmap_details' => 'Voici la liste des fonctionnalités en cours de développement. Abonnez-vous à notre infolettre pour obtenir les mises à jour ou <a href="/contact">Contactez-nous</a> afin d\'influencer la priorité et la direction.',
    ],
    'timezones' => [
        'America/St_Johns' => 'Terre-Neuve (St Johns)',
        'America/Halifax' => 'Atlantique (Halifax)',
        'America/New_York' => 'Est (Montréal)',
        'America/Chicago' => 'Centre (Winnipeg)',
        'America/Denver' => 'Rocheuses (Calgary)',
        'America/Phoenix' => 'Rocheuses heure normale (Phoenix)',
        'America/Los_Angeles' => 'Pacifique (Vancouver)',
        'America/Anchorage' => 'Alaska (Anchorage)',
        'America/Adak' => 'Hawaii (Adak)',
        'Pacific/Honolulu' => 'Hawaii heure normale (Honolulu)',
    ],
    'backend' => [
        'amilia' => [
            'instructions' => 'Instructions',
            'amilia' => 'Amilia',
            'amilia_organizations' => 'Organisations Amilia',
            'amilia_organization' => 'Organisation Amilia',
            'organization' => 'Organisation',
            'name' => 'Nom',
            'logo' => 'Logo',
            'slug' => 'Identifiant de l\'organisation Amilia (ID)',
            'url' => 'Url',
            'email' => 'Courriel',
            'phone' => 'Téléphone',
            'address' => 'Adresse',
            'status' => 'État',
            'connected' => 'Connecté',
            'disconnected' => 'Déconnecté',
            'sync' => 'Synchroniser',
            'synced' => 'Synchronisé',
            'syncing' => 'Synchronisation en cours',
            'sync_failed' => 'Synchronisation échouée',
            'last_synced' => 'Dernière synchronisation',
            'total' => 'organisation total|organisations total',
            'sync_complete' => 'Synchronisation complétée',
            'linked_to_these_organizations' => 'Liée à ces organisations',
            'save' => 'Sauvegarder',
            'linked_organizations_updated' => 'Les liens entre organisations ont été mises à jour',
            'linked' => 'Liaisons',
            'steps' => 'Étapes de liaison vers Amilia',
            'step1' => '1. Donner accès à Activity Messenger',
            'step1a' => 'Connectez-vous à Amilia et allez dans Compte, Administrateurs',
            'step1b' => 'Ajoutez <code>api@activitymessenger.com</code> en tant que gestionnaire niveau 2',
            'step2' => '2. Copier l\'identifiant Amilia',
            'step2a' => 'Toujours dans Amilia, regardez la barre d\'adresse URL de votre navigateur. L\'adresse ressemble à ceci:',
            'step2aa' => '<code>https://www.amilia.com/OrgSettings/fr/organization-slug/AdministratorList</code>',
            'step2ab' => 'La portion <code>organization-slug</code> est l\'identifiant de votre organisation Amilia',
            'step2b' => 'Copier la partie <code>organization-slug</code> et coller la dans le formulaire suivant',
            'can_be_connected_later' => 'Note: Vous pouvez aussi sauter cette étape et lier Amilia plus tard.',
            'connected_help1' => 'Amilia est lié. Vous pouvez tester et gérer la connection ici.',
            'connected_help2' => 'Si vous cherchez plutôt comment faire un envoi à des participants provenants d\'Amilia, vous devez en premier lieu créer une liste. Allez ici:',
        ],
        'access' => [
            'users' => [
                'delete_user_confirm' => 'Êtes-vous sûr de vouloir supprimer cet utilisateur de façon permanente ? Toutes les références à cet utilisateur dans cette application peuvent provoquer des erreurs et cette opération ne peut être annullée.',
                'if_confirmed_off' => '(pour le mode sans confirmation)',
                'restore_user_confirm' => 'Restaurer cet utilisateur à son statut original ?',
            ],
        ],
        'dashboard' => [
            'title' => 'Administration',
            'welcome' => 'Bienvenue',
        ],
        'general' => [
            'all_rights_reserved' => 'Tous droits réservés.',
            'are_you_sure' => 'Êtes-vous sûr ?',
            'boilerplate_link' => 'Laravel Boilerplate',
            'continue' => 'Continuer',
            'member_since' => 'Membre depuis',
            'minutes' => ' minutes.',
            'search_placeholder' => 'Rechercher...',
            'timeout' => 'Vous avez été automatiquement déconnecté pour cause d\'inactivité pendant ',
            'see_all' => [
                'messages' => 'Voir tous les messages',
                'notifications' => 'Voir toutes les notifications',
                'tasks' => 'Voir les nouvelles tâches',
            ],
            'status' => [
                'online' => 'En ligne',
                'offline' => 'Hors ligne',
            ],
            'you_have' => [
                'messages' => "{0} Vous n'avez pas de message|{1} Vous avez 1 message|[2,Inf] Vous avez :number messages",
                'notifications' => "{0} Vous n'avez pas de notification|{1} Vous avez 1 notification|[2,Inf] Vous avez :number notifications",
                'tasks' => "{0} Vous n'avez pas de tâche affectée|{1} Vous avez 1 tâche affectée|[2,Inf] Vous avez :number tâches affectées",
            ],
        ],
        'search' => [
            'empty' => 'Veuillez entrer un terme de recherche.',
            'incomplete' => 'Vous devez mettre en place votre propre logique pour ce système.',
            'title' => 'Résultats de recherche',
            'results' => 'Résultats de la recherche :query',
        ],
        'welcome' => 'Bienvenue au portail administrateur. Accédez à votre page d\'accueil coté client ici:',
    ],
    'emails' => [
        'hello' => 'Bonjour!',
        'whoops' => 'Whoops!',
        'regards' => 'Au plaisir',
        'action_help' => 'Si le bouton ":actionText" ne fonctionne pas, collez/copiez cet hyperlien dans votre navigateur: [:actionURL](:actionURL)',
        'manage_notifications' => 'Gestion des notifications',
        'auth' => [
            'account_confirmed' => 'Votre compte a été confirmé.',
            'error' => 'Oups !',
            'greeting' => 'Bonjour !',
            'regards' => 'Salutations,',
            'trouble_clicking_button' => "Si vous ne pouvez pas cliquer sur le bouton ':action_text', copiez et collez l'URL ci-dessous dans un navigateur:",
            'thank_you_for_using_app' => "Merci d'utiliser notre application!",
            'password_reset_subject' => 'Votre lien de réinitialisation',
            'password_cause_of_email' => 'Vous recevez cet email car nous avons reçu une demande de réinitialisation de mot de passe pour ce compte.',
            'password_if_not_requested' => "Si vous n'avez pas effectué cette demande, aucune autre action n'est requise.",
            'reset_password' => 'Cliquez ici pour réinitialiser votre mot de passe',
            'click_to_confirm' => 'Cliquez ici pour confirmer votre compte:',
        ],
        'contact' => [
            'email_body_title' => 'Vous avez une nouvelle prise de contact dont voici les détails :',
            'subject' => 'Nouvelle soumission du formulaire de contact sur :app_name !',
        ],
        'activation' => [
            'subject' => 'Activer votre compte',
            'greetings' => 'Bonjour :name,',
            'message' => ':name vous a invité à vous joindre à :app pour administrer :org. Veuillez suivre ce lien pour activer votre compte.',
            'activate_account' => 'Activer votre compte',
        ],
        'message' => [
            'subject' => 'Message de :org',
            'greetings' => 'Bonjour :name,',
            'hello' => 'Bonjour,',
            'message_from' => 'Vous avez reçu un message de :name:',
            'received_message' => 'Vous avez reçu un message:',
        ],
    ],
    'frontend' => [
        'test' => 'Test',
        'actions' => 'Actions',
        'tests' => [
            'based_on' => [
                'permission' => 'Helper sur la base de la permissions : ',
                'role' => 'Helper sur la base du rôle : ',
            ],
            'js_injected_from_controller' => 'Javascript injecté depuis un contrôleur',
            'using_blade_extensions' => 'Utilisation des extensions Blade',
            'using_access_helper' => [
                'array_permissions' => "L'utilisateur doit disposer de toutes les permissions d'un tableau, identifiées soit par leur ID, soit par leur nom.",
                'array_permissions_not' => "L'utilisateur doit disposer d'au moins une des permissions d'un tableau, identifiées soit par leur ID, soit par leur nom.",
                'array_roles' => "L'utilisateur doit disposer de tous les rôles d'un tableau, identifiés soit par leur ID, soit par leur nom.",
                'array_roles_not' => "L'utilisateur doit disposer d'au moins un des rôles d'un tableau, identifiés soit par leur ID, soit par leur nom.",
                'permission_id' => "L'utilisateur doit disposer d'une permission identifiée par son ID",
                'permission_name' => "L'utilisateur doit disposer d'une permission identifiée par son nom",
                'role_id' => "L'utilisateur doit disposer d'un rôle identifié par son ID",
                'role_name' => "L'utilisateur doit disposer d'un rôle identifié par son nom",
            ],
            'view_console_it_works' => 'Sur la console du navigateur, vous devriez voir \'it works!\', ce qui est produit depuis le FrontendController@index',
            'you_can_see_because' => 'Vous voyez ce message car vous disposez du rôle \':role\' !',
            'you_can_see_because_permission' => 'Vous voyez ce message car vous disposez de la permission \':permission\' !',
        ],
        'general' => [
            'joined' => 'Membre depuis',
            'none' => 'Aucun',
        ],
        'user' => [
            'change_email_notice' => "Si vous changez votre adresse email vous serez déconnecté jusqu'à que vous confirmiez votre nouvelle adresse email.",
            'email_changed_notice' => 'Vous devez confirmer votre nouvelle adresse email avant de pouvoir vous connecter de nouveau.',
            'profile_updated' => 'Profil modifié avec succès.',
            'password_updated' => 'Mot de passe modifié avec succès.',
            'mobile_updated_confirm_code' => 'Nous vous avons envoyer un code the confirmation. Veuillez le valider afin de terminer la mise à jour.',
            'mobile_updated' => 'Votre téléphone mobile a été confirmé. Vous pouvez maintenant vous en servir.',
            'activation_success' => 'Votre compte est maintenant activé. Vous pouvez vous connecter.',
        ],
        'login_to_access' => "Connectez-vous afin d'accéder à votre page d\'accueil.",
        'or_register' => 'Ou inscrivez-vous pour créer un compte',
        'access_your_dashboard' => 'Bonjour :name. Accédez à votre page d\'accueil.',
        'no_organizations' => "Vous n'avez pas encore créé une organisation.",
        'more' => [
            'need_more_insight' => 'En voulez-vous plus?',
            'contact_us_for_more' => "Contactez-nous. Il nous fera plaisir de concevoir de nouveaux tableaux.",
        ],
    ],
    'dashboard' => [
        'you_have_one_list' => 'Vous avez 1 liste',
        'you_have_many_lists' => 'Vous avez :count listes',
        'you_have_no_lists' => 'Créer votre première liste',
        'you_sent_one_message' => 'Vous avez envoyé 1 message',
        'you_sent_many_messages' => 'Vous avez envoyé :count messages',
        'you_sent_no_messages' => 'Envoyé votre premier message',
        'you_have_one_user' => 'Vous avez 1 collègue',
        'you_have_many_users' => 'Vous avez :count collègues',
        'you_have_no_users' => 'Inviter un collègue',
    ],
    'sms' => [
        'to' => 'À',
        'from' => 'De',
        'message' => 'Message',
        'messages' => 'Messages',
        'send' => 'Envoyer',
        'message_sent' => 'Message envoyé!',
        'validate_code_msg' => 'Votre code de confirmation est :code',
        'confirmed' => 'Confirmé',
        'send_sms' => 'Envoyer un SMS',
        'last_sent_message' => 'Dernier message envoyé le ',
        'no_messages_yet' => 'Vous n\'avec pas encore fait d\'envoi.',
        'goto_messages' => 'Allez voir vos messages',
    ],
    'sendout' => [
        'message' => 'Message',
        'messages' => 'Messages',
        'recent_messages' => 'Messages récents',
        'send' => 'Envoyer',
        'new_message' => 'Nouveau message',
        'message_sent' => 'Message envoyé',
        'under_construction' => 'Chantier en construction',
        'under_construction_details' => 'Nous sommes encore à construire cette page. Pour le moment vous pouvez envoyer un SMS à une liste de personnes ou une seule personne. À terme vous serez en mesure d\'envoyer des courriels aussi.',
        'landing_page' => 'Page web unique',
        'landing_page_details' => 'Chaque message a une page web unique pour ajouter à votre message. Vous serez en mesure d\' joindre documents, calendrier, long message, image, etc...',
        'to' => 'À',
        'sent_on' => 'Envoyé le',
        'status' => 'État',
        'queued' => 'En attente',
        'failed' => 'Échoué',
        'new' => 'Nouveau',
        'sent' => 'Envoyé',
        'delivered' => 'Livré',
        'undelivered' => 'Non livré',
        'skipped' => 'Sauté',
        'sending' => 'Envoi en cours...',
        'error' => 'Erreur',
    ],
    'organization' => [
        'organization' => 'Organisation',
        'organizations' => 'Organisations',
        'add' => 'Ajouter',
        'remove' => 'Retirer',
        'name' => 'Nom',
        'alias' => 'Alias',
        'alias_about' => 'Nom envoyé dans les textos pour vous identifier. Max 20 caractères.',
        'email' => 'Courriel',
        'url' => 'Url',
        'url_of_your_website' => 'Url de votre site Web (facultatif)',
        'reply_to_email' => 'Adresse courriel répondre à',
        'reply_to_email_about' => 'Lorsqu\'un destinataire répondra à un courriel, il sera acheminé à cette adresse. Vous serez aussi en mesure de modifier l\'adresse de retour lors de chaque envoi.',
        'reply_to_mobile' => 'Numéro de téléphone mobile répondre à (facultatif)',
        'reply_to_mobile_about' => 'Lorsqu\'un destinataire répondra à un SMS, il sera acheminé à ce numéro. Vous serez aussi en mesure de modifier le numéro de retour lors de chaque envoi.',
        'timezone' => 'Fuseau horaire',
        'new_organization' => 'Nouvelle organisation',
        'organization_created' => 'L\'organisation a été créée',
        'organization_updated' => 'L\'organisation a été mise à jour',
        'organization_deleted' => 'L\'organisation a été effacée',
        'are_you_sure_delete' => 'Veuillez confirmer votre intention d\'effacer cette organisation.',
        'connect' => 'Lier',
        'amilia' => 'Amilia',
        'connect_to_amilia' => 'Lier à Amilia',
        'connection_to_amilia' => 'Liaison vers Amilia',
        'connected_to_amilia' => 'Lié à Amilia',
        'manage_amilia_connection' => 'Gérer le lien vers Amilia',
        'amilia_connected_success' => 'Amilia est maintenant lié',
        'disconnect' => 'Retirer le lien',
        'is_connected_to_amilia' => ':name est lié à Amilia.',
        'amilia_disconnected_success' => 'Le lien vers Amilia a été retiré. Les listes tirées d\'Amilia ne fonctionneront plus. Vous pouvez rétablir le lien.',
        'amilia_already_disconnected' => 'Le lien vers Amilia était déjà rompu.',
        'yes' => 'Oui',
        'no' => 'Non',
        'your_clients' => 'Your clients',
        'users' => 'Utilisateurs',
        'user' => 'Utilisateur',
        'users_about' => 'Les individus ayant accès',
        'email_confirmed' => 'Courriel confirmé',
        'user_added' => 'Utilisateur ajouté',
        'user_removed' => 'Utilisateur retiré',
        'settings' => 'Configuration',
        'modify_information' => 'Modifier les informations',
        'modify_organization_information' => 'Modifier les informations de l\'organisation',
        'balance' => 'Solde',
        'payment_error' => 'Erreur lors du paiement: :status',
        'orders' => 'Commandes',
        'date' => 'Date',
        'amount' => 'Montant',
        'all_messages' => 'Consultez tous les messages',
        'all_lists' => 'Consultez toutes les listes',
        'logo' => 'Logo',
        'branding' => 'L\'image de marque',
        'edit_branding' => 'Mettre à jour l\'image de marque de votre organisation',
        'header' => 'Entête',
        'header_about' => 'Ajuster le visuel de l\'entête des courriels que vous envoyez à vos participants, ainsi que les pages Web.',
        'general' => 'General',
        'messaging' => 'Messagerie',
        'amilia_integration' => 'Intégration Amilia',
        'reply_to_mobile_preference' => 'Préférence de réponse SMS',
        'reply_to_mobile_preference_about' => 'Quoi faire quand un participant répond à un de vos messages. Lors d\'un envoi, vous pourrez modifier ce choix.',
        'forward_organization' => 'Faire suivre le message au numéro mobile "répondre à" de l\'organisation',
        'forward_sender' => 'Faire suivre le message au numéro mobile de l\'utilisateur qui fait l\'envoi',
        'auto_reply' => 'Répondre avec un message automatisé',
        'do_nothing' => 'Ne rien faire',
        'mobile_auto_reply_message' => 'Réponse automatisée pour le SMS',
        'default_mobile_auto_reply_message' => 'Je suis un robot',
    ],
    'orguser' => [
        'manage_users' => 'Gestion des utilisateurs',
        'user' => 'Utilisateur',
        'users' => 'Utilisateurs',
        'about' => 'Voici les gestionnaires de cette organisation. Ces personnes peuvent: créer des listes, faire des envois de messagers et ajouter des utilisateurs.',
        'add' => 'Ajouter',
        'name' => 'Nom',
        'mobile' => 'Mobile',
        'email' => 'Courriel',
        'add_a_user' => 'Ajouter un utilisateur',
        'add_about' => 'Cette personne pourra gérer cette organisation: créer des listes, faire des envois de messagers et ajouter d\'autres utilisateurs.',
        'permissions' => 'Permissions',
        'existing_user_added' => ':name a déjà un compte et a été ajouté comme utilisateur de cette organisation. Vous pouvez lui laisser savoir.',
        'new_user_added' => ':name n\'a pas encore de compte. On lui a envoyé un courriel d\'activation. Une fois activé, il/elle aura accès à cette organisation.',
    ],
    'lists' => [
        'list' => 'Liste',
        'lists' => 'Listes',
        'recent_lists' => 'Listes récentes',
        'name' => 'Nom',
        'description' => 'Description',
        'recipients' => 'Destinataires',
        'number_of_recipients' => 'Nombre de destinataires',
        'sent_on' => 'Date d\'envoi',
        'success_rate' => 'Taux reçu',
        'information' => 'Information',
        'new_list' => 'Nouvelle liste',
        'create' => 'Créer',
        'list_created' => 'La nouvelle liste a été créée',
        'list_updated' => 'La liste a été mise à jour',
        'modify' => 'Modifier',
        'delete' => 'Effacer',
        'archive' => 'Archiver',
        'update' => 'Mettre à jour',
        'are_you_sure_delete' => 'Veuillez confirmer votre intention d\'effacer cette liste.',
        'yes_delete' => 'Oui effacer',
        'cancel' => 'Annuler',
        'list_deleted' => 'La liste a été effacée',
        'type' => 'Type',
        'type_csv' => 'CSV (données que vous saisissez ou copiez d\'une autre application)',
        'type_amilia_import_program' => 'Programmation vivante Amilia (participants inscrits à une programmation)',
        'last_updated' => 'Mise à jour',
    ],
    'newsletter' => [
        'newsletter' => 'Infolettre',
        'newsletters' => 'Infolettres',
        'recent_newsletters' => 'Infolettres récentes',
        'new_newsletter' => 'Nouvelle infolettre',
        'newsletter_created' => 'La nouvelle infolettre a été créée',
        'newsletter_updated' => 'L\'infolettre a été mise à jour',
        'are_you_sure_delete' => 'Veuillez confirmer votre intention d\'effacer cette infolettre.',
        'newsletter_deleted' => 'L\'infolettre a été effacée',
    ],
    'blacklist' => [
        'blacklist' => 'Rebondis',
        'blacklist_about' => 'Les destinataires qui se sont désinscrits. Cette liste comprend aussi les mauvais numéros de téléphone ainsi que les plaintes et rebondis.',
        'remove_success' => 'Le destinataire a été enlevé de la liste des rebondis.',
    ],
    'onboarding' => [
        'checklist' => 'Étapes de configuration',
        'complete_these_steps' => 'Completer ces étapes pour terminer la configuration de votre compte.',
        'add_mobile_phone' => 'Ajouter votre téléphone mobile',
        'confirm_your_mobile' => 'Confirmer votre téléphone mobile',
        'create_an_organization' => 'Créer une organisation',
        'create_a_list' => 'Creer une liste',
        'onboarding_complete' => 'Votre compte est configuré. Nous ajouterons de nouvelles tâches quand de nouvelles fonctionnalités seront disponibles.',
        'send_first_sms' => 'Envoyer un texto',
        'preview' => 'Aperçu',
        'powered_by' => 'Propulsé par',
    ],
    'help' => [
        'support' => 'Support',
        'instructions' => 'Vous avez besoin d\'un coup de main? Vous avez une demande d\'amélioration? Contactez-nous par courriel:',
        'copy_instructions' => 'Si ce bouton n\'ouvre pas votre Messagerie, cliquez sur le bouton droit de votre sourie, et choisissez: Copier l\'adresse courriel.',
    ],
    'landing' => [
        'message' => 'message',
        'you_received_a_message_from' => 'Vous avez reçu un message de ',
        'allow_org_to_send_me_emails' => 'Permettre :org de m\'envoyer des courriels',
        'allow_org_to_send_me_sms' => 'Permettre :org de m\'envoyer des textos',
        'save' => 'Sauvegarder',
        'notifications_updated' => 'Vos paramètres de notifications ont été mis à jour.',
    ],
];
